from building import *

cwd = GetCurrentDir()

# Only compile essential board support files
src = Split("""
    board.c
    rtt_board.c
    pinmux.c
""")

CPPPATH = [cwd]
CPPDEFINES=['D45', 'HPM6E80']

group = DefineGroup('Board', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)

Return('group')
